name: TgHomeBot CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:

  buildAndPush:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create image tag
      id: imageTag
      run: |
        branch=${{ github.ref_name }}
        echo "tag=${branch//'/'/'-'}-${{ github.run_number }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: metaApi
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/tghomebot-api
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.imageTag.outputs.tag }}

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./TgHomeBot.Api/Dockerfile
        push: true
        tags: ${{ steps.metaApi.outputs.tags }}
        labels: ${{ steps.metaApi.outputs.labels }}

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.24.0
      with:
        image: ${{ env.REGISTRY }}/thomasneuberger/tghomebot-api:${{ steps.imageTag.outputs.tag }}
        artifact-name: sbom-${{ steps.imageTag.outputs.tag }}.spdx.json
        output-file: sbom.spdx.json
        format: spdx-json

    - name: Output image tag
      run: echo "Image tag ${{ steps.imageTag.outputs.tag }} published" >> $GITHUB_STEP_SUMMARY
