name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:

  buildAndPush:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create image tag
      id: imageTag
      run: |
        branch=${{ github.ref_name }}
        echo "tag=${branch//'/'/'-'}-${{ github.run_number }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: metaApi
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/thomasneuberger/tghomebot-api
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.imageTag.outputs.tag }}

      # https://github.com/docker/build-push-action#inputs
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./TgHomeBot.Api/Dockerfile
        push: true
        tags: ${{ steps.metaApi.outputs.tags }}
        labels: ${{ steps.metaApi.outputs.labels }}
