name: TgHomeBot CI

on: [ pull_request, workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the docker image
      run: docker build . --file ./TgHomeBot.Api/Dockerfile --tag tghomebot:latest
